name: Unit testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

permissions:
  contents: read

jobs:
  unit-testing:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Unit & Integration tests
        run: >
          pnpm run coverage
          --
          --coverage.reporter json
          --coverage.reporter json-summary
          --coverage.reporter text
        env:
          FORCE_COLOR: 1

      - name: Merge coverage reports
        run: pnpm run report
        env:
          FORCE_COLOR: 1

      - name: Upload coverage report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: coverage-prev
          path: packages/config-vitest/coverage/report/coverage-summary.json

      - name: Download previous coverage report
        # renovate: datasource=github-releases depName=dawidd6/action-download-artifact
        uses: dawidd6/action-download-artifact@20319c5641d495c8a52e688b7dc5fada6c3a9fbc # v11
        if: success() && github.event.number
        with:
          name: coverage-prev
          workflow: unit-testing.yml
          branch: ${{ github.event.pull_request.base.ref || github.event.repository.default_branch }}
          path: ./coverage-prev

      - name: Coverage in GitHub PR comment
        uses: davelosert/vitest-coverage-report-action@8ab049ff5a2c6e78f78af446329379b318544a1a # v2.8.3
        with:
          file-coverage-mode: all
          json-final-path: ${{ github.workspace }}/packages/config-vitest/coverage/merged/merged-coverage.json
          json-summary-path: ${{ github.workspace }}/packages/config-vitest/coverage/report/coverage-summary.json
          json-summary-compare-path: |
            ${{ github.event_name == 'pull_request' && 'coverage-prev/coverage-summary.json' || null }}
          vite-config-path: ${{ github.workspace }}/packages/config-vitest/vitest.config.ts
